### ISSUE TITLE
[Glitch] `Error handshaking` when running from source

### ISSUE THREAD

**Issue by TFWol** [umageddon/namDHC#11]
Just mostly an FYI, when running from source, getting handshake error:
```
Handshaking with namDHC..................Error handshaking!
```

Afterwards need to restart program to get back to working condition.

Compiling the script and running works fine.

**Comment by umageddon** [comment]
namdhc respawns itself as separate processes when running. Its an autohotkey version of 'threads'.
Windows will see the threads and main app as Autohotkey.exe and trying to determine by app name becomes difficult.
