### ISSUE TITLE
[Feature Request] Report to show before and after file sizes

### ISSUE THREAD

**Issue by TFWol** [umageddon/namDHC#13]
I see the ratio while it's working, but I think most people would like to see the size savings in the post report since I feel it's the reason most people would use chadman.

Maybe something like: 
File | Size Before | Size After | Percent
--- | --- | --- | ---

or whatever; I'm not a UX designer or anything.

**Comment by umageddon** [comment]
Thanks for the suggestion. Its now in v1.13
