### ISSUE TITLE
Latest version is flagged as a trojan 

### ISSUE THREAD

**Issue by michaeljota** [umageddon/namDHC#18]
After downloading the latest version through the updater, it is flagged as a trojan.

**Comment by umageddon** [comment]
Is Window defender flagging it?

**Comment by umageddon** [comment]
If you like you can compile yourself with source code or just re-download the version separately and just install it over your old version.
If its Defender, I think Windows might be seeing the update routine as some form of self modifying code??  Not really sure why a few people are having the issue. Over my head anyway
