### ISSUE TITLE
Suggestion for a new feature: Extract CHD to Multi-Bin/Cue

### ISSUE THREAD

**Issue by TomTurbine** [umageddon/namDHC#19]
I have tested something out and had it work, so could potentially add it in a new release but would require a secondary app to go with it.
BinMerge: https://github.com/putnam/binmerge

It can split the single bin file that CHDMan puts out based on the cue sheet into the multiple bin files. Actually tested it doing this with a PSX game and it matched the original Bin/Cue files I started with.

Would be a good automated way to be able to revert a CHD collection of ReDump games back to the Bin/Cue setup their Dat files expected.

Just have it extract a game back into a bin/cue, then run that through BinMerge and keep the final product it ended up with, then move onto the next one.

**Comment by TomTurbine** [comment]
As an extension this to,

If you could have it setup where it extracted CD based discs to Multi-Track Bin/Cue and DVD based to ISO, it would actually allow you to just extract to ReDump dats perfectly which many would love to see automated. But I think that could potentially be a lock of checks and work to get done.

**Comment by umageddon** [comment]
Sorry the program will remain a simple frontend to chdman at this time. 
I just dont have the time currently to add any major features like this. 

Maybe someday
