### ISSUE TITLE
Files with capitalized extensions can't be added

### ISSUE THREAD

**Issue by SkyNinja** [umageddon/namDHC#23]
Disk images with capitalized file extensions can be selected in the OS file select dialogue, but are immediately removed by manDHC, appearing in the UI for a split second.

**Comment by umageddon** [comment]
Thanks for the feedback, will look into it

**Comment by PlzHlpWithFansly** [comment]
Thank you for noting this, I was scratching my head on a ROM that just wouldn't show up and this ended up being the problem.  Renaming the extension fixed it for me.

**Comment by PlzHlpWithFansly** [comment]
> Thanks for the feedback, will look into it

Doesn't seem this is fixed in the latest release.  I was able to recreate the problem with a .CUE file containing capp'd extension.  As soon as I renamed the file extension with lowercase chars, it worked no problem.

**Comment by alebustelo** [comment]
This is still a problem as of the latest version.
