### ISSUE TITLE
Feature: 7zip Support

### ISSUE THREAD

**Issue by Andrewpaps** [umageddon/namDHC#26]
Would be handy to have 7zip as as select-able input type as myself and many others are batch converting from large 7zip archives or libraries.

**Comment by umageddon** [comment]
Ive though about doing this in the past but currently i just dont have the time. 
It also means packaging another executable with the bundle and more complexity then was originally intended. 
Its a front end for chdman - thats it. 
I may change my mind if I can find time to put more work into the project. 

Thanks for the suggestion thou.
