### ISSUE TITLE
[Enhancement] Adds support for converting chd files to iso!

### ISSUE THREAD

**Issue by INDRAPhilip** [umageddon/namDHC#3]
I think the chd file and everything it brings is amazing, but sometimes we like to make changes to the original files like changing a game texture or files in the game code and in chd it's not as practical as in iso so I'd love a way to convert chd to iso!

**Comment by umageddon** [comment]
Chdman dosent support converting images to ISO. This tool is merely a front-end for CHDMAN. 
Maybe sometime in the future I could think of adding additional features, but for now its going to stay just a front-end.
