### ISSUE TITLE
Support for special Latin characters

### ISSUE THREAD

**Issue by dezraj** [umageddon/namDHC#4]
Hello! I was trying to convert a PS1 game from BIN/CUE to CHD with this tool but it returned an error. The game is a Spanish hack for King of Fighters Kyo. Here's the log:

"CREATECD - The King of Fighters Kyo Hack Español.chd
─────────────────────────────────────────────────────────────────────────────
Error parsing input file (D:\unzipped\games\PlayStation\The King of Fighters Kyo Hack EspaÃ±ol.cue: No such file or directory)

Fatal error occurred: 1

Successfully created"

It says "successfully created" but the conversion doesn't happen at all.

I suppose the issue is related with the special Latin character which exists in the BIN/CUE files.

I don't know if this could be fixed in the GUI level, but I am reporting it here anyway.

Thank you  so much for your work.

**Comment by IceLancerSR** [comment]
Another problem , but this one might be related to 255character limmit , chdman alone does job but tool throws error like urs
Ace Combat 5 - The Unsung War (USA) (En,Ja)

**Comment by umageddon** [comment]
Unsure at this time. 
May be an Autohotkey issue? You can try the latest version see if it works, 
When I have time, I will look into this.
