### ISSUE TITLE
Create new folder from the GUI

### ISSUE THREAD

**Issue by dezraj** [umageddon/namDHC#5]
Hello!

I converted some PS2 games to the folder "PS2 CHD" and then after completion this folder was kept as a suggestion for "output folder". Then I converted some PS1 games but first I renamed the output folder to "PS1 CHD". For my surprise the games were placed in the same "PS2 CHD" folder which I had configured before.

I suppose this happened because I didn't have a "PS1 CHD" folder created in the specified path, so it used the one which had worked before perhaps?

Would it be possible for the GUI to create the folder which has been inserted/typed in the "output folder" field when it cannot find it the configured path?

I felt the need for this because I like to compare the size of the original folder with the uncompressed files with the new folder with the compressed CHD files, and when we have games from various different systems it is more convenient to this directly from the GUI instead of doing it from the Windows Explorer.

Another possibility would be to prompt the user about the creation of the folder with a message such as "The folder X was not found in the specified path. Would you like to create it?". But for me it's easier and quicker to just create it without any prompts.

I don't know if this would be possible in the GUI level, so forgive me for my request.

Thank you so much for your work.

**Comment by umageddon** [comment]
Did you hit enter to confirm the folder change?

**Comment by dezraj** [comment]
> Did you hit enter to confirm the output folder change?

Hello! If I remember correctly, I think I didn't. I just edited the previous folder path with one I wanted to be created (in the same drive).

Would hitting the Enter key trigger the creation of a new folder from the GUI?

Thank you for your time.

**Comment by dezraj** [comment]
Hello! I tested converting another ISO and hitting Enter in the path string this time it did created the new folder.

So what could be fixed perhaps would be detecting if the inserted path exists or not (and if not, create it) even when the user doesn't hit Enter in that field (which might happen eventually).

Thank you anyway for your attention.

**Comment by umageddon** [comment]
This is fixed in v1.08
