### ISSUE TITLE
Windows Defender issue

### ISSUE THREAD

**Issue by BillCipher-exe** [umageddon/namDHC#6]
Auto update from v1.06 -> v1.07 triggers a Windows Defender warning ("Trojan:Script/Conteban.A!ml"). results in automatic deletion of the namDHC.exe

**Comment by umageddon** [comment]
What? Lol thats weird. Ill check it out at home. Source code is on github if you want to compile manually

**Comment by SteveStation** [comment]
> 
I may be wrong but the problem may be that the versions of the files are the same  and the windows defender triggers a false warning.
