### ISSUE TITLE
Qol Feature Request , Split cue 

### ISSUE THREAD

**Issue by IceLancerSR** [umageddon/namDHC#7]
Hello!
chdman has a known flaw , that merges multiple bin files into a single one when converting back from chd.. And it will result in non functional game. The program does this with all cd images with multiple tracks separated into their own bin files. When it extracts the data, it keeps the tracks in the same file. 

So game has cue and 1,2,3,4,+x bin files convert to chd works fine.
Now u try to revert to original state and you get 1 cue and 1 large bin file

To resolve this, you'll have to get a third party program to split the files. I've recently tested a python 3 script that seems to work perfect.
[https://github.com/putnam/binmerge](url)
Using command 
binmerge.exe --split "test.cue" extractoriginal
tool is able to restore original bin files by reading cue data and they match original hash data.

So , my request is to either coordinate with binmrge or add same functionality to your tool. And make the process done simpler.

Thanks!

P.S
if someone else stumbles here, looking for help i was using this batch file to restore file. But for the sake of not messing up , it will rename new file and data in cue to match new file , meaning it would became test-original.cue
this line command needs to be written in somefilename.cmd Note: If you rename bin/cue after spliting, you also have to EDIT cue data to match new file name.

for /r %%i in (*.cue) do binmerge --split "%%i" "%%~ni-original"
[binmerge_CUE_splitter.zip](https://github.com/umageddon/namDHC/files/9144174/binmerge_CUE_splitter.zip)

**Comment by umageddon** [comment]
Sorry this is beyond what the program is written for at this time.  Maybe in the future with more time. Thanks for the input!
