### ISSUE TITLE
255 characters path , breaks tool

### ISSUE THREAD

**Issue by IceLancerSR** [umageddon/namDHC#8]
Hello.
Maybe make tool to read relative pathing instead of  absolute, in order to fix 255character limit?
If path to file is over that length , app will break with error.

**Comment by umageddon** [comment]
This is a Autohotkey and a Windows issue.  Nothing I can do at this time.

**Comment by IceLancerSR** [comment]
Fine, what ever man. Ill leave this as Note: Autohotkey script does not have any issues launched from any depth.
